name: Workflow Events

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 */5 * * *' 
  workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Event name:${{ github.event_name }}"

